# Generated by Django 5.0.6 on 2024-07-04 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='نام ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت')),
                ('pr_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تولید')),
                ('exp_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انقضا')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='برند')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
