# Generated by Django 5.0.6 on 2024-07-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
