# Generated by Django 5.0.6 on 2024-09-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_cart_user_cart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='pr_date',
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر'),
        ),
    ]
