# Generated by Django 5.1.1 on 2024-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_productinfo_brand_remove_productinfo_exp_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='category',
            field=models.TextField(null=True, verbose_name='دسته بندی'),
        ),
    ]
