# Generated by Django 5.1.1 on 2024-09-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_delete_category_productinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/shop', verbose_name='تصویر'),
        ),
    ]
