# Generated by Django 5.1.1 on 2024-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.CharField(default=0, max_length=10, verbose_name='قیمت'),
        ),
    ]
